"""generic access and workspace ownership

Revision ID: 3836580891fe
Revises: 4bd8a81af4b4
Create Date: 2026-08-13 18:53:02.343572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3836580891fe'
down_revision: Union[str, None] = '4bd8a81af4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    # Local development historically used metadata.create_all().  It may have
    # created these new empty tables before Alembic is run, so tolerate their
    # presence while still applying every column/backfill operation below.
    existing_tables = set(sa.inspect(connection).get_table_names())
    if 'auth_access_roles' not in existing_tables:
        op.create_table('auth_access_roles',
        sa.Column('role_id', sa.String(length=36), nullable=False),
        sa.Column('organization_id', sa.String(length=36), nullable=False),
        sa.Column('role_key', sa.String(length=80), nullable=False),
        sa.Column('display_name', sa.String(length=120), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=False),
        sa.Column('is_system', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['auth_organizations.organization_id'], ),
        sa.PrimaryKeyConstraint('role_id'),
        sa.UniqueConstraint('organization_id', 'role_key', name='uq_auth_role_org_key')
        )
        op.create_index(op.f('ix_auth_access_roles_organization_id'), 'auth_access_roles', ['organization_id'], unique=False)
    if 'auth_membership_permissions' not in existing_tables:
        op.create_table('auth_membership_permissions',
        sa.Column('membership_permission_id', sa.String(length=36), nullable=False),
        sa.Column('membership_id', sa.String(length=36), nullable=False),
        sa.Column('permission', sa.String(length=240), nullable=False),
        sa.Column('effect', sa.String(length=10), nullable=False),
        sa.Column('assigned_by_user_id', sa.String(length=36), nullable=True),
        sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['membership_id'], ['auth_memberships.membership_id'], ),
        sa.PrimaryKeyConstraint('membership_permission_id'),
        sa.UniqueConstraint('membership_id', 'permission', name='uq_auth_membership_permission')
        )
        op.create_index(op.f('ix_auth_membership_permissions_membership_id'), 'auth_membership_permissions', ['membership_id'], unique=False)
    if 'auth_membership_roles' not in existing_tables:
        op.create_table('auth_membership_roles',
        sa.Column('membership_role_id', sa.String(length=36), nullable=False),
        sa.Column('membership_id', sa.String(length=36), nullable=False),
        sa.Column('role_id', sa.String(length=36), nullable=False),
        sa.Column('assigned_by_user_id', sa.String(length=36), nullable=True),
        sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['membership_id'], ['auth_memberships.membership_id'], ),
        sa.ForeignKeyConstraint(['role_id'], ['auth_access_roles.role_id'], ),
        sa.PrimaryKeyConstraint('membership_role_id'),
        sa.UniqueConstraint('membership_id', 'role_id', name='uq_auth_membership_role')
        )
        op.create_index(op.f('ix_auth_membership_roles_membership_id'), 'auth_membership_roles', ['membership_id'], unique=False)
        op.create_index(op.f('ix_auth_membership_roles_role_id'), 'auth_membership_roles', ['role_id'], unique=False)
    if 'auth_role_permissions' not in existing_tables:
        op.create_table('auth_role_permissions',
        sa.Column('role_permission_id', sa.String(length=36), nullable=False),
        sa.Column('role_id', sa.String(length=36), nullable=False),
        sa.Column('permission_pattern', sa.String(length=240), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['auth_access_roles.role_id'], ),
        sa.PrimaryKeyConstraint('role_permission_id'),
        sa.UniqueConstraint('role_id', 'permission_pattern', name='uq_auth_role_permission')
        )
        op.create_index(op.f('ix_auth_role_permissions_role_id'), 'auth_role_permissions', ['role_id'], unique=False)
    organization_id = connection.execute(
        sa.text("SELECT organization_id FROM auth_organizations ORDER BY created_at LIMIT 1")
    ).scalar()
    if organization_id is None:
        organization_id = "00000000-0000-0000-0000-000000000001"
        connection.execute(
            sa.text(
                "INSERT INTO auth_organizations "
                "(organization_id, name, slug, is_active, created_at) "
                "VALUES (:id, 'Migrated Workspace', 'migrated-workspace', 1, CURRENT_TIMESTAMP)"
            ),
            {"id": organization_id},
        )

    op.add_column('br_exceptions', sa.Column('organization_id', sa.String(length=36), nullable=True))
    op.add_column('br_exceptions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('br_exceptions', sa.Column('updated_by_user_id', sa.String(length=36), nullable=True))
    connection.execute(
        sa.text("UPDATE br_exceptions SET organization_id = :id WHERE organization_id IS NULL"),
        {"id": organization_id},
    )
    with op.batch_alter_table('br_exceptions') as batch_op:
        batch_op.alter_column('organization_id', existing_type=sa.String(length=36), nullable=False)
    op.create_index(op.f('ix_br_exceptions_organization_id'), 'br_exceptions', ['organization_id'], unique=False)
    op.add_column('br_reconciliations', sa.Column('organization_id', sa.String(length=36), nullable=True))
    op.add_column('br_reconciliations', sa.Column('updated_by_user_id', sa.String(length=36), nullable=True))
    connection.execute(
        sa.text("UPDATE br_reconciliations SET organization_id = :id WHERE organization_id IS NULL"),
        {"id": organization_id},
    )
    with op.batch_alter_table('br_reconciliations') as batch_op:
        batch_op.alter_column('organization_id', existing_type=sa.String(length=36), nullable=False)
        batch_op.drop_index(op.f('ix_br_reconciliations_reference'))
        batch_op.create_index(op.f('ix_br_reconciliations_reference'), ['reference'], unique=False)
        batch_op.create_unique_constraint('uq_br_reconciliation_org_reference', ['organization_id', 'reference'])
    op.create_index(op.f('ix_br_reconciliations_organization_id'), 'br_reconciliations', ['organization_id'], unique=False)
    op.add_column('je_review_entries', sa.Column('organization_id', sa.String(length=36), nullable=True))
    op.add_column('je_review_entries', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('je_review_entries', sa.Column('created_by_user_id', sa.String(length=36), nullable=True))
    op.add_column('je_review_entries', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('je_review_entries', sa.Column('updated_by_user_id', sa.String(length=36), nullable=True))
    connection.execute(
        sa.text(
            "UPDATE je_review_entries SET organization_id = :id, "
            "created_at = COALESCE(created_at, CURRENT_TIMESTAMP)"
        ),
        {"id": organization_id},
    )
    with op.batch_alter_table('je_review_entries') as batch_op:
        batch_op.alter_column('organization_id', existing_type=sa.String(length=36), nullable=False)
        batch_op.alter_column('created_at', existing_type=sa.DateTime(timezone=True), nullable=False)
    op.create_index(op.f('ix_je_review_entries_organization_id'), 'je_review_entries', ['organization_id'], unique=False)
    op.add_column('je_reviews', sa.Column('organization_id', sa.String(length=36), nullable=True))
    op.add_column('je_reviews', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('je_reviews', sa.Column('updated_by_user_id', sa.String(length=36), nullable=True))
    connection.execute(
        sa.text("UPDATE je_reviews SET organization_id = :id WHERE organization_id IS NULL"),
        {"id": organization_id},
    )
    with op.batch_alter_table('je_reviews') as batch_op:
        batch_op.alter_column('organization_id', existing_type=sa.String(length=36), nullable=False)
    op.create_index(op.f('ix_je_reviews_organization_id'), 'je_reviews', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('je_reviews') as batch_op:
        batch_op.drop_index(op.f('ix_je_reviews_organization_id'))
        batch_op.drop_column('updated_by_user_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('organization_id')
    with op.batch_alter_table('je_review_entries') as batch_op:
        batch_op.drop_index(op.f('ix_je_review_entries_organization_id'))
        batch_op.drop_column('updated_by_user_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('organization_id')
    with op.batch_alter_table('br_reconciliations') as batch_op:
        batch_op.drop_constraint('uq_br_reconciliation_org_reference', type_='unique')
        batch_op.drop_index(op.f('ix_br_reconciliations_organization_id'))
        batch_op.drop_index(op.f('ix_br_reconciliations_reference'))
        batch_op.create_index(op.f('ix_br_reconciliations_reference'), ['reference'], unique=True)
        batch_op.drop_column('updated_by_user_id')
        batch_op.drop_column('organization_id')
    with op.batch_alter_table('br_exceptions') as batch_op:
        batch_op.drop_index(op.f('ix_br_exceptions_organization_id'))
        batch_op.drop_column('updated_by_user_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('organization_id')
    op.drop_index(op.f('ix_auth_role_permissions_role_id'), table_name='auth_role_permissions')
    op.drop_table('auth_role_permissions')
    op.drop_index(op.f('ix_auth_membership_roles_role_id'), table_name='auth_membership_roles')
    op.drop_index(op.f('ix_auth_membership_roles_membership_id'), table_name='auth_membership_roles')
    op.drop_table('auth_membership_roles')
    op.drop_index(op.f('ix_auth_membership_permissions_membership_id'), table_name='auth_membership_permissions')
    op.drop_table('auth_membership_permissions')
    op.drop_index(op.f('ix_auth_access_roles_organization_id'), table_name='auth_access_roles')
    op.drop_table('auth_access_roles')
    # ### end Alembic commands ###
