"""local totp authentication foundation

Revision ID: 4bd8a81af4b4
Revises: b82e7c341a10
Create Date: 2026-08-13 17:49:46.833845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd8a81af4b4'
down_revision: Union[str, None] = 'b82e7c341a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_bootstrap_state',
    sa.Column('marker', sa.String(length=40), nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('administrator_user_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('marker')
    )
    op.create_table('auth_login_throttles',
    sa.Column('throttle_key', sa.String(length=64), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('throttle_key')
    )
    op.create_table('auth_organizations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_index(op.f('ix_auth_organizations_slug'), 'auth_organizations', ['slug'], unique=True)
    op.create_table('auth_users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('normalized_email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('identity_assurance', sa.String(length=40), nullable=False),
    sa.Column('asserted_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('asserted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_auth_users_is_active'), 'auth_users', ['is_active'], unique=False)
    op.create_index(op.f('ix_auth_users_normalized_email'), 'auth_users', ['normalized_email'], unique=True)
    op.create_table('auth_credentials',
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('credential_type', sa.String(length=40), nullable=False),
    sa.Column('encrypted_secret', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('encryption_key_id', sa.String(length=100), nullable=False),
    sa.Column('last_accepted_counter', sa.Integer(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.user_id'], ),
    sa.PrimaryKeyConstraint('credential_id')
    )
    op.create_index(op.f('ix_auth_credentials_revoked_at'), 'auth_credentials', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_auth_credentials_user_id'), 'auth_credentials', ['user_id'], unique=False)
    op.create_table('auth_external_identities',
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('issuer', sa.String(length=500), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.user_id'], ),
    sa.PrimaryKeyConstraint('identity_id'),
    sa.UniqueConstraint('issuer', 'subject', name='uq_auth_external_issuer_subject')
    )
    op.create_index(op.f('ix_auth_external_identities_user_id'), 'auth_external_identities', ['user_id'], unique=False)
    op.create_table('auth_memberships',
    sa.Column('membership_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['auth_organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.user_id'], ),
    sa.PrimaryKeyConstraint('membership_id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_auth_membership_org_user')
    )
    op.create_index(op.f('ix_auth_memberships_organization_id'), 'auth_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_auth_memberships_status'), 'auth_memberships', ['status'], unique=False)
    op.create_index(op.f('ix_auth_memberships_user_id'), 'auth_memberships', ['user_id'], unique=False)
    op.create_table('auth_recovery_codes',
    sa.Column('recovery_code_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('code_hmac', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.user_id'], ),
    sa.PrimaryKeyConstraint('recovery_code_id')
    )
    op.create_index(op.f('ix_auth_recovery_codes_code_hmac'), 'auth_recovery_codes', ['code_hmac'], unique=True)
    op.create_index(op.f('ix_auth_recovery_codes_user_id'), 'auth_recovery_codes', ['user_id'], unique=False)
    op.create_table('auth_enrollment_tokens',
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('membership_id', sa.String(length=36), nullable=False),
    sa.Column('token_hmac', sa.String(length=64), nullable=False),
    sa.Column('encrypted_totp_secret', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('encryption_key_id', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['membership_id'], ['auth_memberships.membership_id'], ),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    op.create_index(op.f('ix_auth_enrollment_tokens_expires_at'), 'auth_enrollment_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_enrollment_tokens_membership_id'), 'auth_enrollment_tokens', ['membership_id'], unique=False)
    op.create_index(op.f('ix_auth_enrollment_tokens_token_hmac'), 'auth_enrollment_tokens', ['token_hmac'], unique=True)
    op.create_table('auth_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('membership_id', sa.String(length=36), nullable=False),
    sa.Column('token_hmac', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idle_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['membership_id'], ['auth_memberships.membership_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_auth_sessions_absolute_expires_at'), 'auth_sessions', ['absolute_expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_idle_expires_at'), 'auth_sessions', ['idle_expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_membership_id'), 'auth_sessions', ['membership_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_revoked_at'), 'auth_sessions', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_token_hmac'), 'auth_sessions', ['token_hmac'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_token_hmac'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_revoked_at'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_membership_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_idle_expires_at'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_absolute_expires_at'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_auth_enrollment_tokens_token_hmac'), table_name='auth_enrollment_tokens')
    op.drop_index(op.f('ix_auth_enrollment_tokens_membership_id'), table_name='auth_enrollment_tokens')
    op.drop_index(op.f('ix_auth_enrollment_tokens_expires_at'), table_name='auth_enrollment_tokens')
    op.drop_table('auth_enrollment_tokens')
    op.drop_index(op.f('ix_auth_recovery_codes_user_id'), table_name='auth_recovery_codes')
    op.drop_index(op.f('ix_auth_recovery_codes_code_hmac'), table_name='auth_recovery_codes')
    op.drop_table('auth_recovery_codes')
    op.drop_index(op.f('ix_auth_memberships_user_id'), table_name='auth_memberships')
    op.drop_index(op.f('ix_auth_memberships_status'), table_name='auth_memberships')
    op.drop_index(op.f('ix_auth_memberships_organization_id'), table_name='auth_memberships')
    op.drop_table('auth_memberships')
    op.drop_index(op.f('ix_auth_external_identities_user_id'), table_name='auth_external_identities')
    op.drop_table('auth_external_identities')
    op.drop_index(op.f('ix_auth_credentials_user_id'), table_name='auth_credentials')
    op.drop_index(op.f('ix_auth_credentials_revoked_at'), table_name='auth_credentials')
    op.drop_table('auth_credentials')
    op.drop_index(op.f('ix_auth_users_normalized_email'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_is_active'), table_name='auth_users')
    op.drop_table('auth_users')
    op.drop_index(op.f('ix_auth_organizations_slug'), table_name='auth_organizations')
    op.drop_table('auth_organizations')
    op.drop_table('auth_login_throttles')
    op.drop_table('auth_bootstrap_state')
    # ### end Alembic commands ###