"""Initial schema - platform + bank_reconciliation + journal_entry_review

Revision ID: fa11f6602989
Revises:
Create Date: 2026-08-13 13:06:02.217252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa11f6602989'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('br_reconciliations',
    sa.Column('reconciliation_id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'MATCHED', 'EXCEPTION', 'APPROVED', 'CLOSED', name='reconciliationstatus'), nullable=False),
    sa.Column('statement_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('book_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('reconciliation_id')
    )
    op.create_index(op.f('ix_br_reconciliations_reference'), 'br_reconciliations', ['reference'], unique=True)
    op.create_table('je_reviews',
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('engagement', sa.String(length=200), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('source_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('UNREVIEWED', 'IN_REVIEW', 'FLAGGED', 'APPROVED', 'REJECTED', name='jereviewstatus'), nullable=False),
    sa.Column('total_entries', sa.Integer(), nullable=False),
    sa.Column('flagged_count', sa.Integer(), nullable=False),
    sa.Column('approved_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('platform_jobs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_code', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('input_artifact_ids', sa.JSON(), nullable=True),
    sa.Column('output_artifact_ids', sa.JSON(), nullable=True),
    sa.Column('result_meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_platform_jobs_correlation_id'), 'platform_jobs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_platform_jobs_module'), 'platform_jobs', ['module'], unique=False)
    op.create_index(op.f('ix_platform_jobs_status'), 'platform_jobs', ['status'], unique=False)
    op.create_table('br_exceptions',
    sa.Column('exception_id', sa.String(length=36), nullable=False),
    sa.Column('reconciliation_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('account', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('UNMATCHED', 'IN_REVIEW', 'RESOLVED', 'ESCALATED', name='exceptionstatus'), nullable=False),
    sa.Column('match_candidate', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['br_reconciliations.reconciliation_id'], ),
    sa.PrimaryKeyConstraint('exception_id')
    )
    op.create_index(op.f('ix_br_exceptions_reconciliation_id'), 'br_exceptions', ['reconciliation_id'], unique=False)
    op.create_table('je_review_entries',
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('je_number', sa.String(length=50), nullable=False),
    sa.Column('account', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('posting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('UNREVIEWED', 'IN_REVIEW', 'FLAGGED', 'APPROVED', 'REJECTED', name='jereviewstatus'), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['je_reviews.review_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_table('platform_artifacts',
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('storage_uri', sa.String(length=1000), nullable=False),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('source_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['platform_jobs.job_id'], ),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['platform_artifacts.artifact_id'], ),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_index(op.f('ix_platform_artifacts_artifact_type'), 'platform_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_platform_artifacts_created_at'), 'platform_artifacts', ['created_at'], unique=False)
    op.create_table('platform_evidence',
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('locator', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['platform_artifacts.artifact_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_platform_evidence_entity_id'), 'platform_evidence', ['entity_id'], unique=False)
    op.create_index(op.f('ix_platform_evidence_module'), 'platform_evidence', ['module'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_evidence_module'), table_name='platform_evidence')
    op.drop_index(op.f('ix_platform_evidence_entity_id'), table_name='platform_evidence')
    op.drop_table('platform_evidence')
    op.drop_index(op.f('ix_platform_artifacts_created_at'), table_name='platform_artifacts')
    op.drop_index(op.f('ix_platform_artifacts_artifact_type'), table_name='platform_artifacts')
    op.drop_table('platform_artifacts')
    op.drop_table('je_review_entries')
    op.drop_index(op.f('ix_br_exceptions_reconciliation_id'), table_name='br_exceptions')
    op.drop_table('br_exceptions')
    op.drop_index(op.f('ix_platform_jobs_status'), table_name='platform_jobs')
    op.drop_index(op.f('ix_platform_jobs_module'), table_name='platform_jobs')
    op.drop_index(op.f('ix_platform_jobs_correlation_id'), table_name='platform_jobs')
    op.drop_table('platform_jobs')
    op.drop_table('je_reviews')
    op.drop_index(op.f('ix_br_reconciliations_reference'), table_name='br_reconciliations')
    op.drop_table('br_reconciliations')
    # ### end Alembic commands ###
